package v1porject_mc;


import v1porject_mc.PatientDemographics;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static v1porject_mc.AllergyHistory.PatientID;
import static v1porject_mc.PatientDemographics.getCurrentPatientID;
import static v1porject_mc.PatientDemographics.tabledemographics;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author sharylriley
 */



public class GeneralMedicalHistory extends javax.swing.JFrame {
    public GeneralMedicalHistory()
    {
        
    }
    /**
     * Creates new form PatientDemographics
     */
    public GeneralMedicalHistory(String patientID) {
        initComponents();
        //author sara rodriguez 
        initializePatientIdField(patientID);
        table_update();
        
        //author Sharyl Riley
        //enable form to edit
        isNew = false;
        //change form background color to lightgrey
        backGround = Color.lightGray;
        toggleEditAndBackground();
        
        
    
  
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralMedicalHistory = new javax.swing.JPanel();
        buttonAllergyHisForm = new javax.swing.JButton();
        buttonImmunizationHisForm = new javax.swing.JButton();
        buttonMedicationHisForm = new javax.swing.JButton();
        buttonGenHisAutoInterview = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonSaveGenMedHis = new javax.swing.JButton();
        buttonEditGenMedHis = new javax.swing.JButton();
        buttonDeleteGenMedHis = new javax.swing.JButton();
        buttonAddGenMedHis = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        GeneralMedicalHistoryID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonFamilyHisForm = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Tobacco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TobaccoQuanity = new javax.swing.JTextField();
        TobaccoDuration = new javax.swing.JTextField();
        buttonCloseGenMedHisForm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BloodType = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Rh = new javax.swing.JTextField();
        Alcohol = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AlcoholQuanity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Alcoholduration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Drug = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DrugType = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Drugduration = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGenMedHis = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        PatientID = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAllergyHisForm.setText("Allergy History Form");
        buttonAllergyHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllergyHisFormActionPerformed(evt);
            }
        });

        buttonImmunizationHisForm.setText("Immunization History Form");
        buttonImmunizationHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImmunizationHisFormActionPerformed(evt);
            }
        });

        buttonMedicationHisForm.setText("Medication History Form");
        buttonMedicationHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicationHisFormActionPerformed(evt);
            }
        });

        buttonGenHisAutoInterview.setText("Start General Medical History Automated Interview ");
        buttonGenHisAutoInterview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenHisAutoInterviewActionPerformed(evt);
            }
        });

        jLabel2.setText("General Medical History Form");

        buttonSaveGenMedHis.setText("Save Record");
        buttonSaveGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveGenMedHisActionPerformed(evt);
            }
        });

        buttonEditGenMedHis.setText("Edit Selected Record");
        buttonEditGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditGenMedHisActionPerformed(evt);
            }
        });

        buttonDeleteGenMedHis.setText("Delete Selected Record");
        buttonDeleteGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteGenMedHisActionPerformed(evt);
            }
        });

        buttonAddGenMedHis.setText("Add New Medical History Record");
        buttonAddGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddGenMedHisActionPerformed(evt);
            }
        });

        jLabel3.setText("General Medical History ID:");

        GeneralMedicalHistoryID.setEditable(false);
        GeneralMedicalHistoryID.setBackground(java.awt.Color.pink);

        jLabel8.setText("jLabel8");

        jLabel15.setText("Access Forms:");

        buttonFamilyHisForm.setText("Family History Form");
        buttonFamilyHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFamilyHisFormActionPerformed(evt);
            }
        });

        jLabel28.setText("Tobacco::");

        jLabel29.setText("Alcohol:");

        jLabel5.setText("Tobacco Quanity:");

        jLabel6.setText("Tobacco Duration:");

        buttonCloseGenMedHisForm.setText("Close");
        buttonCloseGenMedHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseGenMedHisFormActionPerformed(evt);
            }
        });

        jLabel7.setText("Blood Type:");

        jLabel9.setText("rH Factor:");

        Rh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RhActionPerformed(evt);
            }
        });

        jLabel10.setText("Alcohol Quanity:");

        jLabel11.setText("Alcohol Duration:");

        jLabel12.setText("Drug:");

        jLabel13.setText("Drug Type:");

        jLabel14.setText("Drug Duration:");

        tableGenMedHis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "General Medical History ID", "Blood Type"
            }
        ));
        tableGenMedHis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGenMedHisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGenMedHis);

        jLabel4.setText("Patient ID:");

        PatientID.setEditable(false);
        PatientID.setBackground(java.awt.Color.pink);

        UpdateButton.setText("Update Data");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GeneralMedicalHistoryLayout = new javax.swing.GroupLayout(GeneralMedicalHistory);
        GeneralMedicalHistory.setLayout(GeneralMedicalHistoryLayout);
        GeneralMedicalHistoryLayout.setHorizontalGroup(
            GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(726, 726, 726))
            .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                            .addComponent(buttonAddGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonEditGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonDeleteGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSaveGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonCloseGenMedHisForm))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel29)
                                .addComponent(jLabel12)
                                .addComponent(jLabel5)
                                .addComponent(jLabel28))
                            .addGap(18, 18, 18)
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tobacco)
                                .addComponent(Drugduration)
                                .addComponent(TobaccoQuanity)
                                .addComponent(TobaccoDuration)
                                .addComponent(AlcoholQuanity)
                                .addComponent(Alcoholduration)
                                .addComponent(Drug)
                                .addComponent(DrugType)
                                .addComponent(Alcohol)))
                        .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(58, 58, 58))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                                    .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(BloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Rh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(GeneralMedicalHistoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel4)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                    .addGap(107, 107, 107)
                                    .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addComponent(buttonAllergyHisForm)
                                        .addComponent(buttonFamilyHisForm)))
                                .addComponent(buttonImmunizationHisForm, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(buttonMedicationHisForm, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateButton)
                    .addComponent(buttonGenHisAutoInterview))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        GeneralMedicalHistoryLayout.setVerticalGroup(
            GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel15)
                        .addGap(8, 8, 8)
                        .addComponent(buttonAllergyHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFamilyHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImmunizationHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMedicationHisForm))
                    .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddGenMedHis)
                    .addComponent(buttonEditGenMedHis)
                    .addComponent(buttonDeleteGenMedHis)
                    .addComponent(buttonSaveGenMedHis)
                    .addComponent(buttonCloseGenMedHisForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UpdateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonGenHisAutoInterview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GeneralMedicalHistoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(PatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Rh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(BloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Tobacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TobaccoQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TobaccoDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AlcoholQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Alcoholduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Drug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DrugType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Drugduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralMedicalHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralMedicalHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //author sara rodriguez 
     private void table_update()
    {
        int c;
        
      

        //register the driver class
        //initialize
        String dburl = "jdbc:mysql://localhost:3306/genmedhis?autoconnect=true&useSSL=false"; //connection string of the database
        String InsertSql = "Select * FROM generalmedicalhistorytable WHERE PatientID =" + PatientID.getText();
        String dbOutput;
        
        try
        {
        //register the driver class
        //initialize
            Class.forName("com.mysql.cj.jdbc.Driver");
            //actual connect with login
            Connection con = DriverManager.getConnection(dburl, "root", "P@ssw0rd");
            PreparedStatement ps = con.prepareStatement(InsertSql);
      
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(InsertSql);
            
            ResultSetMetaData Rss = rs.getMetaData();
            c = Rss.getColumnCount();
            
            DefaultTableModel Df = (DefaultTableModel)tableGenMedHis.getModel();
            Df.setRowCount(0);
           
           //inserts into jTable column and rows
                while(rs.next())
                {
                    PatientID.setText(rs.getString("PatientID")) ;

                    Vector v2 = new Vector();
                    
                    for(int a=1; a<=c; a++)
                    {
                        v2.add(rs.getString("GeneralMedicalHistoryID"));
                        v2.add(rs.getString("BloodType"));
                    }
                    
                   
                    Df.addRow(v2);
                }
           
            con.close(); //close connection
        }
        
        catch(SQLException e)
        {
            System.out.println("Error exceuting INSERT Operation!");
            e.printStackTrace();
        }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
    
    }
    
    
    private void buttonMedicationHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicationHisFormActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
         //calls Medication History Form
        MedicationHistory form = new MedicationHistory(getCurrentPatientID());
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonMedicationHisFormActionPerformed

    private void buttonSaveGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveGenMedHisActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        isNew = false;
        //change form background color to lightgrey
        backGround = Color.lightGray;
        toggleEditAndBackground();
       
        //author sara rodriguez 
        String tobacco = Tobacco.getText();
        String tobaccoquanity = TobaccoQuanity.getText();
        String tobaccoduration = TobaccoDuration.getText();
        String alcohol = Alcohol.getText();
        String alcoholquanity = AlcoholQuanity.getText();
        String alcoholduration = Alcoholduration.getText();
        String drug = Drug.getText();
        String drugtype = DrugType.getText();
        String drugduration = Drugduration.getText(); 
        String bloodtype = BloodType.getText();
        String rh = Rh.getText();
        initializePatientIdField(PatientID.getText());
        
       
        
        String InsertSql = "INSERT INTO generalmedicalhistorytable ( Tobacco, TobaccoQuantity, Tobaccoduraton, "
                + "Alcohol, AlcoholQuantity, Alcoholduration, Drug, DrugType, Drugduration, BloodType, Rh, PatientID) "
                + " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
     
        //insert record
        try
        {
            DefaultTableModel Df = (DefaultTableModel) tabledemographics.getModel();
        
            int selectedRowIndex = tabledemographics.getSelectedRow();
            int PatientID = Integer.parseInt(Df.getValueAt(selectedRowIndex,0).toString());
            //register drive class
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dburl, "root","P@ssw0rd");
            PreparedStatement ps = con.prepareStatement(InsertSql);
            
            
            ps.setString(1, tobacco); //1 = first ? from above
            ps.setString(2, tobaccoquanity);//2 = second ? from above
            ps.setString(3, tobaccoduration);
            ps.setString(4, alcohol);
            ps.setString(5, alcoholquanity);
            ps.setString(6, alcoholduration);
            ps.setString(7, drug);
            ps.setString(8, drugtype);
            ps.setString(9, drugduration);
            ps.setString(10, bloodtype);
            ps.setString(11, rh);
            ps.setInt(12,PatientID);
            int rowCount = ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Added Succesfully");
            
            //makes textfields back to blank
            resetTextInTableGenMed();
            
            
            table_update();
            con.close();
            
        }
        catch(SQLException e)
        {
            
            System.out.println("Error executing INSERT Operation");
            e.printStackTrace();
        }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
 

    }//GEN-LAST:event_buttonSaveGenMedHisActionPerformed

    private void RhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RhActionPerformed

    private void buttonEditGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditGenMedHisActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        //enable form to edit
        isNew = true;
        backGround = Color.WHITE;
        toggleEditAndBackground();
        
        
        //author sara rodriguez 
        String InsertSql = ("select * from generalmedicalhistorytable WHERE GeneralMedicalHistoryID=" ) + GeneralMedicalHistoryID.getText();
        try
        {
            
        //initialize
            Class.forName("com.mysql.cj.jdbc.Driver");
            //actual connect with login
            Connection con = DriverManager.getConnection(dburl, "root", "P@ssw0rd");
            PreparedStatement ps = con.prepareStatement(InsertSql); //insert statement from above
            
            Statement  stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(InsertSql);
            
            //displays ALL information into jTextfields
            while(rs.next())
            {
                GeneralMedicalHistoryID.setText(rs.getString("GeneralMedicalHistoryID"));
                BloodType.setText(rs.getString("BloodType"));
                Rh.setText(rs.getString("Rh"));
                Tobacco.setText(rs.getString("Tobacco"));
                TobaccoQuanity.setText(rs.getString("TobaccoQuantity"));
                TobaccoDuration.setText(rs.getString("Tobaccoduraton"));
                Alcohol.setText(rs.getString("Alcohol"));
                AlcoholQuanity.setText(rs.getString("AlcoholQuantity"));
                Alcoholduration.setText(rs.getString("Alcoholduration"));
                Drug.setText(rs.getString("Drug"));
                DrugType.setText(rs.getString("DrugType"));
                Drugduration.setText(rs.getString("Drugduration")); 
                BloodType.setText(rs.getString("BloodType"));
                Rh.setText(rs.getString("Rh"));
            
            }
            
             con.close(); //close connection
        }
        
        catch(SQLException e)
        {
            System.out.println("Error exceuting EDIT Operation!");
            e.printStackTrace();
        }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
      
        //author sara rodriguez 
        //call the getter currentPatientID
        getCurrentPatientID();
        
        
        
    }//GEN-LAST:event_buttonEditGenMedHisActionPerformed

    private void buttonAllergyHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllergyHisFormActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        // calls Allergy Form
        AllergyHistory form = new AllergyHistory(getCurrentPatientID());
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAllergyHisFormActionPerformed

    private void buttonFamilyHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFamilyHisFormActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        //calls Familiy History Form
        FamilyHistory form = new FamilyHistory(getCurrentPatientID());
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonFamilyHisFormActionPerformed

    private void buttonImmunizationHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImmunizationHisFormActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        // calls Immunization Form
        ImmunizationHistory form = new ImmunizationHistory(getCurrentPatientID());
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonImmunizationHisFormActionPerformed

    private void buttonAddGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddGenMedHisActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        isNew = true;
        backGround = Color.WHITE;
        toggleEditAndBackground();
        resetTextInTableGenMed();
       
        
        
    }//GEN-LAST:event_buttonAddGenMedHisActionPerformed

    private void buttonDeleteGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteGenMedHisActionPerformed
        // TODO add your handling code here:
        
        //author sara rodriguez 
       
        String InsertSQL = "DELETE from generalmedicalhistorytable WHERE generalmedicalhistoryID=?"; 
        try
        {
        //register the driver class
        //initialize
            Class.forName("com.mysql.cj.jdbc.Driver");
            //actual connect with login
            Connection con = DriverManager.getConnection(dburl, "root", "P@ssw0rd");
            PreparedStatement ps = con.prepareStatement(InsertSQL); //insert statement from above
            
             //1 = first ? from above
            ps.setString(1, GeneralMedicalHistoryID.getText());
            ps.executeUpdate();
            con.close(); //close connection
        }
        
        catch(SQLException e)
        {
            System.out.println("Error exceuting INSERT Operation!");
            e.printStackTrace();
        }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
        
        //CODE BELOW REMOVES ROW FROM JTABLE
        
        
        DefaultTableModel tblModel = (DefaultTableModel) tableGenMedHis.getModel();
        
        //delete row
        if(tableGenMedHis.getSelectedRowCount()==1)
        {
            tblModel.removeRow(tableGenMedHis.getSelectedRow());
        }
        else
        {
            if(tableGenMedHis.getRowCount()==0)
            {
                //if table is empty(no data) than display message
                JOptionPane.showMessageDialog(this, "Table is empty.");
            }
            else //if table isnt empty but user did not select a row
            {
                JOptionPane.showMessageDialog(this, "Please select a row to be deleted.");
            }
        }
        
        JOptionPane.showMessageDialog(null, "Patient data is removed.");
        resetTextInTableGenMed();
    }//GEN-LAST:event_buttonDeleteGenMedHisActionPerformed

    private void buttonCloseGenMedHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseGenMedHisFormActionPerformed
        // TODO add your handling code here:
        
        //author Sharyl Riley
        //goes back to Patient Demographic Form
        //calls Medication History Form
        PatientDemographics form = new PatientDemographics ();
        form.setVisible(true);
        this.setVisible(false);
        resetTextInTableGenMed();
    }//GEN-LAST:event_buttonCloseGenMedHisFormActionPerformed

    private void buttonGenHisAutoInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenHisAutoInterviewActionPerformed
        // TODO add your handling code here:
        
        //Author Sharyl Riley April 17, 2021
        //calles decisiontreeclass genmed automated interview method
        DecisionTreeClass.runGenMedAutomatedInterview();
    }//GEN-LAST:event_buttonGenHisAutoInterviewActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        //author sharyl riley
        isNew = false;
        backGround = Color.lightGray;
        toggleEditAndBackground();
        
        
        //author sara rodriguez 
        DefaultTableModel Df = (DefaultTableModel) tableGenMedHis.getModel();
        
        int selectedRowIndex = tableGenMedHis.getSelectedRow();

      
        String InsertSQL = "UPDATE generalmedicalhistorytable SET Tobacco=?, TobaccoQuantity=?, Tobaccoduraton=?, Alcohol=?, AlcoholQuantity=?, "
                + "Alcoholduration=?, Drug=?, DrugType=?, Drugduration=?, BloodType=?, Rh=? where GeneralMedicalHistoryID=?"; 
        
        //UPDATES MYSQLDATABASE
        try
        {
            int generalMedicalHistoryID = Integer.parseInt(Df.getValueAt(selectedRowIndex,0).toString());
        //register the driver class
        //initialize
            Class.forName("com.mysql.cj.jdbc.Driver");
            //actual connect with login
            Connection con = DriverManager.getConnection(dburl, "root", "P@ssw0rd");
            PreparedStatement ps = con.prepareStatement(InsertSQL); //insert statement from above
            String tobacco = Tobacco.getText();
            String tobaccoquanity = TobaccoQuanity.getText();
            String tobaccoduration = TobaccoDuration.getText();
            String alcohol = Alcohol.getText();
            String alcoholquanity = AlcoholQuanity.getText();
            String alcoholduration = Alcoholduration.getText();
            String drug = Drug.getText();
            String drugtype = DrugType.getText();
            String drugduration = Drugduration.getText(); 
            String bloodtype = BloodType.getText();
            String rh = Rh.getText();
            
            ps.setString(1, tobacco); //1 = first ? from above
            ps.setString(2, tobaccoquanity);//2 = second ? from above
            ps.setString(3, tobaccoduration);
            ps.setString(4, alcohol);
            ps.setString(5, alcoholquanity);
            ps.setString(6, alcoholduration);
            ps.setString(7, drug);
            ps.setString(8, drugtype);
            ps.setString(9, drugduration);
            ps.setString(10, bloodtype);
            ps.setString(11, rh);
            ps.setInt(12, generalMedicalHistoryID);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record was Updated");
            table_update();
            //reset text
            resetTextInTableGenMed();
            
            
            con.close(); //close connection
        }
        
        catch(SQLException e)
        {
            System.out.println("Error exceuting UPDATING Operation!");
            e.printStackTrace();
        }
        catch(ClassNotFoundException e)
        {
            e.printStackTrace();
        }
        

    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void tableGenMedHisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGenMedHisMouseClicked
        // TODO add your handling code here:
        
        //author sara rodriguez 
        DefaultTableModel Df = (DefaultTableModel)tableGenMedHis.getModel();
         int selectedIndex = tableGenMedHis.getSelectedRow();
     
        //displays information which clicking on a record
        GeneralMedicalHistoryID.setText(Df.getValueAt(selectedIndex, 0).toString());
        BloodType.setText(Df.getValueAt(selectedIndex, 1).toString());
    }//GEN-LAST:event_tableGenMedHisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralMedicalHistory(PatientDemographics.getCurrentPatientID()).setVisible(true);
            }
        });
    }
    
    //author Sharyl Riley
    private static void toggleEditAndBackground(){
        //Makes textfields non editable
        Tobacco.setEditable(isNew);
        TobaccoQuanity.setEditable(isNew);
        TobaccoDuration.setEditable(isNew);
        Alcohol.setEditable(isNew);
        AlcoholQuanity.setEditable(isNew);
        Alcoholduration.setEditable(isNew);
        Drug.setEditable(isNew);
        DrugType.setEditable(isNew);
        Drugduration.setEditable(isNew); 
        BloodType.setEditable(isNew);
        Rh.setEditable(isNew);
        
        //makes background default color lightGray
        Tobacco.setBackground(backGround);
        TobaccoQuanity.setBackground(backGround);
        TobaccoDuration.setBackground(backGround);
        Alcohol.setBackground(backGround);
        AlcoholQuanity.setBackground(backGround);
        Alcoholduration.setBackground(backGround);
        Drug.setBackground(backGround);
        DrugType.setBackground(backGround);
        Drugduration.setBackground(backGround); 
        BloodType.setBackground(backGround);
        Rh.setBackground(backGround);
    }
    //Author Sharyl Riley
    private static void resetTextInTableGenMed(){
        
        //resets text
        GeneralMedicalHistoryID.setText("");
        BloodType.setText("");
        Rh.setText("");
        Tobacco.setText("");
        TobaccoQuanity.setText("");
        TobaccoDuration.setText("");
        Alcohol.setText("");
        AlcoholQuanity.setText("");
        Alcoholduration.setText("");
        Drug.setText("");
        DrugType.setText("");
        Drugduration.setText("");
        BloodType.setText("");
        
        
    }
    
    //author sara rodriguez 
    private static void initializePatientIdField(String patientID)
    {
        PatientID.setText(patientID); //used to pass PatientID
    }
    
    
    //Author Sharyl Riley
    // variables for toggleEditAndBackground Method
    private static boolean isNew = false;
    private static Color backGround = Color.LIGHT_GRAY;
    private static String currentPatientID;
    private static String dburl = "jdbc:mysql://localhost:3306/genmedhis?autoconnect=true&useSSL=false"; //connection string of the database

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Alcohol;
    public static javax.swing.JTextField AlcoholQuanity;
    public static javax.swing.JTextField Alcoholduration;
    public static javax.swing.JTextField BloodType;
    public static javax.swing.JTextField Drug;
    public static javax.swing.JTextField DrugType;
    public static javax.swing.JTextField Drugduration;
    private javax.swing.JPanel GeneralMedicalHistory;
    public static javax.swing.JTextField GeneralMedicalHistoryID;
    public static javax.swing.JTextField PatientID;
    public static javax.swing.JTextField Rh;
    public static javax.swing.JTextField Tobacco;
    public static javax.swing.JTextField TobaccoDuration;
    public static javax.swing.JTextField TobaccoQuanity;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton buttonAddGenMedHis;
    private javax.swing.JButton buttonAllergyHisForm;
    private javax.swing.JButton buttonCloseGenMedHisForm;
    private javax.swing.JButton buttonDeleteGenMedHis;
    private javax.swing.JButton buttonEditGenMedHis;
    private javax.swing.JButton buttonFamilyHisForm;
    private javax.swing.JButton buttonGenHisAutoInterview;
    private javax.swing.JButton buttonImmunizationHisForm;
    private javax.swing.JButton buttonMedicationHisForm;
    private javax.swing.JButton buttonSaveGenMedHis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tableGenMedHis;
    // End of variables declaration//GEN-END:variables
}
