CREATE SCHEMA IF NOT EXISTS genmedhis;
use genmedhis;
drop table if exists patienttable;
CREATE TABLE `patienttable` (
`PatientID` int(11) NOT NULL AUTO_INCREMENT, 
`PtLastName` varchar(128) DEFAULT NULL, 
`PtPreviousLastName` varchar(128) DEFAULT NULL, 
`PtFirstName` varchar(128) DEFAULT NULL, 
`HomeAddress1` varchar(128) DEFAULT NULL, 
`HomeAddress2` varchar(128) DEFAULT NULL,
`HomeCity` varchar(128) DEFAULT NULL, 
`HomeState/Province/Region` varchar(50) DEFAULT NULL,
`HomeZip` varchar(15) DEFAULT NULL,
`Country` varchar(75) DEFAULT NULL,
`Citizenship` varchar(75) DEFAULT NULL, 
`PtHomePhone` varchar(14) DEFAULT NULL, 
`EmergencyPhoneNumber` varchar(14) DEFAULT NULL, 
`EmailAddress` varchar(128) DEFAULT NULL,
`PtSS#` varchar(12) DEFAULT NULL,
`DOB` datetime DEFAULT NULL,
`Gender` varchar(50) DEFAULT NULL, 
`EthnicAssociation` varchar(75) DEFAULT NULL, 
`MaritalStatus` varchar(25) DEFAULT NULL, 
`CurrentPrimaryHCPId` varchar(128) DEFAULT NULL, 
`Active` tinyint(1) DEFAULT '1',
`Comments` varchar(254) DEFAULT NULL, 
`SubscriberRelationship` varchar(10) DEFAULT NULL,
`NextOfKin` varchar(128) DEFAULT NULL,
`PtMiddleInitial` varchar(4) DEFAULT NULL, 
`NextOfKinRelationshipToPatient` varchar(50) DEFAULT NULL, 
PRIMARY KEY (`PatientID`),
KEY `I_PtLastFirstName` (`PtLastName`,`PtFirstName`),
KEY `I_HomePhone` (`PtHomePhone`),
KEY `I_SSN` (`PtSS#`)
);