/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author sharylriley
 */
public class FamilyHistory extends javax.swing.JFrame {

    /**
     * Creates new form PatientDemographics
     */
    public FamilyHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonGenMedHisForm = new javax.swing.JButton();
        buttonImmunizationHisForm = new javax.swing.JButton();
        buttonMedicationHisForm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonSaveFamiliyMem = new javax.swing.JButton();
        buttonEditFamiliyMem = new javax.swing.JButton();
        buttonDeleteFamiliyMem = new javax.swing.JButton();
        buttonAddFamiliyMem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        FamilyID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonAllergyHisForm = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MajorDisorder = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Relation = new javax.swing.JTextField();
        buttonCloseFamiliyMemForm = new javax.swing.JButton();
        SpecificTypeDisorder = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CheckBoxDisorderHRF = new javax.swing.JCheckBox();
        CheckBoxAlive = new javax.swing.JCheckBox();
        checkboxLivesWPatient = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select Family Record");

        buttonGenMedHisForm.setText("General Medical History Form");
        buttonGenMedHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenMedHisFormActionPerformed(evt);
            }
        });

        buttonImmunizationHisForm.setText("Immunization History Form");
        buttonImmunizationHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImmunizationHisFormActionPerformed(evt);
            }
        });

        buttonMedicationHisForm.setText("Medication History Form");
        buttonMedicationHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicationHisFormActionPerformed(evt);
            }
        });

        jLabel2.setText("Family History Form");

        buttonSaveFamiliyMem.setText("Save Family Record");
        buttonSaveFamiliyMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveFamiliyMemActionPerformed(evt);
            }
        });

        buttonEditFamiliyMem.setText("Edit Selected Family Member");
        buttonEditFamiliyMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditFamiliyMemActionPerformed(evt);
            }
        });

        buttonDeleteFamiliyMem.setText("Delete Selected Family Member");
        buttonDeleteFamiliyMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteFamiliyMemActionPerformed(evt);
            }
        });

        buttonAddFamiliyMem.setText("Add New Family Member");
        buttonAddFamiliyMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddFamiliyMemActionPerformed(evt);
            }
        });

        jLabel3.setText("Family ID:");

        jLabel8.setText("jLabel8");

        jLabel15.setText("Access Forms:");

        buttonAllergyHisForm.setText("Allergy History Form");
        buttonAllergyHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllergyHisFormActionPerformed(evt);
            }
        });

        jLabel28.setText("Name:");

        jLabel29.setText(" Major Disorder:");

        MajorDisorder.setText(" ");

        jLabel5.setText("Relation:");

        buttonCloseFamiliyMemForm.setText("Close");
        buttonCloseFamiliyMemForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseFamiliyMemFormActionPerformed(evt);
            }
        });

        SpecificTypeDisorder.setText(" ");
        SpecificTypeDisorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecificTypeDisorderActionPerformed(evt);
            }
        });

        jLabel7.setText("Specific Type Disorder:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Family ID", "Name", "Relation"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CheckBoxDisorderHRF.setText("Disorder HRF");

        CheckBoxAlive.setText("Alive");

        checkboxLivesWPatient.setText("Lives with Patient");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(checkboxLivesWPatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxAlive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxDisorderHRF)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(726, 726, 726))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonGenMedHisForm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonAllergyHisForm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonImmunizationHisForm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonMedicationHisForm, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonAddFamiliyMem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSaveFamiliyMem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDeleteFamiliyMem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonEditFamiliyMem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCloseFamiliyMemForm)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FamilyID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Relation)))
                        .addGap(0, 789, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(MajorDisorder)
                        .addContainerGap())))
            .addComponent(SpecificTypeDisorder)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel15))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(buttonGenMedHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonAllergyHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImmunizationHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(buttonMedicationHisForm)
                        .addGap(210, 210, 210))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAddFamiliyMem)
                            .addComponent(buttonSaveFamiliyMem)
                            .addComponent(buttonDeleteFamiliyMem)
                            .addComponent(buttonEditFamiliyMem)
                            .addComponent(buttonCloseFamiliyMemForm))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(FamilyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Relation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkboxLivesWPatient)
                            .addComponent(CheckBoxAlive)
                            .addComponent(CheckBoxDisorderHRF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)))
                .addComponent(MajorDisorder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpecificTypeDisorder, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMedicationHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicationHisFormActionPerformed
        // TODO add your handling code here:
         //calls Medication History Form
        MedicationHistory form = new MedicationHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonMedicationHisFormActionPerformed

    private void buttonImmunizationHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImmunizationHisFormActionPerformed
        // TODO add your handling code here:
        // calls Immunization Form
        ImmunizationHistory form = new ImmunizationHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonImmunizationHisFormActionPerformed

    private void buttonEditFamiliyMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditFamiliyMemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEditFamiliyMemActionPerformed

    private void SpecificTypeDisorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecificTypeDisorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpecificTypeDisorderActionPerformed

    private void buttonGenMedHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenMedHisFormActionPerformed
        // TODO add your handling code here:
        GeneralMedicalHistory form = new GeneralMedicalHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonGenMedHisFormActionPerformed

    private void buttonAllergyHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllergyHisFormActionPerformed
        // TODO add your handling code here:
        // calls Allergy Form
        AllergyHistory form = new AllergyHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAllergyHisFormActionPerformed

    private void buttonAddFamiliyMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddFamiliyMemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddFamiliyMemActionPerformed

    private void buttonSaveFamiliyMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveFamiliyMemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveFamiliyMemActionPerformed

    private void buttonDeleteFamiliyMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteFamiliyMemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteFamiliyMemActionPerformed

    private void buttonCloseFamiliyMemFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseFamiliyMemFormActionPerformed
        // TODO add your handling code here:
        //calls Medication History Form
        PatientDemographics form = new PatientDemographics ();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonCloseFamiliyMemFormActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxAlive;
    private javax.swing.JCheckBox CheckBoxDisorderHRF;
    private javax.swing.JTextField FamilyID;
    private javax.swing.JTextField MajorDisorder;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Relation;
    private javax.swing.JTextField SpecificTypeDisorder;
    private javax.swing.JButton buttonAddFamiliyMem;
    private javax.swing.JButton buttonAllergyHisForm;
    private javax.swing.JButton buttonCloseFamiliyMemForm;
    private javax.swing.JButton buttonDeleteFamiliyMem;
    private javax.swing.JButton buttonEditFamiliyMem;
    private javax.swing.JButton buttonGenMedHisForm;
    private javax.swing.JButton buttonImmunizationHisForm;
    private javax.swing.JButton buttonMedicationHisForm;
    private javax.swing.JButton buttonSaveFamiliyMem;
    private javax.swing.JCheckBox checkboxLivesWPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
