/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author sharylriley
 */
public class GeneralMedicalHistory extends javax.swing.JFrame {

    /**
     * Creates new form PatientDemographics
     */
    public GeneralMedicalHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GeneralMedicalHistory = new javax.swing.JPanel();
        buttonAllergyHisForm = new javax.swing.JButton();
        buttonImmunizationHisForm = new javax.swing.JButton();
        buttonMedicationHisForm = new javax.swing.JButton();
        buttonGenHisAutoInterview = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buttonSaveGenMedHis = new javax.swing.JButton();
        buttonEditGenMedHis = new javax.swing.JButton();
        buttonDeleteGenMedHis = new javax.swing.JButton();
        buttonAddGenMedHis = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        GeneralMedicalHistoryID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        buttonFamilyHisForm = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Tobacco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TobaccoQuanity = new javax.swing.JTextField();
        TobaccoDuration = new javax.swing.JTextField();
        buttonCloseGenMedHisForm = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        BloodType = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Rh = new javax.swing.JTextField();
        Alcohol = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        AlcoholQuanity = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Alcoholduration = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Drug = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        DrugType = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Drugduration = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAllergyHisForm.setText("Allergy History Form");
        buttonAllergyHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAllergyHisFormActionPerformed(evt);
            }
        });

        buttonImmunizationHisForm.setText("Immunization History Form");
        buttonImmunizationHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonImmunizationHisFormActionPerformed(evt);
            }
        });

        buttonMedicationHisForm.setText("Medication History Form");
        buttonMedicationHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMedicationHisFormActionPerformed(evt);
            }
        });

        buttonGenHisAutoInterview.setText("Start General Medical History Automated Interview ");
        buttonGenHisAutoInterview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenHisAutoInterviewActionPerformed(evt);
            }
        });

        jLabel2.setText("General Medical History Form");

        buttonSaveGenMedHis.setText("Save Record");
        buttonSaveGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveGenMedHisActionPerformed(evt);
            }
        });

        buttonEditGenMedHis.setText("Edit Selected Record");
        buttonEditGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditGenMedHisActionPerformed(evt);
            }
        });

        buttonDeleteGenMedHis.setText("Delete Selected Record");
        buttonDeleteGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteGenMedHisActionPerformed(evt);
            }
        });

        buttonAddGenMedHis.setText("Add New Medical History Record");
        buttonAddGenMedHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddGenMedHisActionPerformed(evt);
            }
        });

        jLabel3.setText("General Medical History ID:");

        jLabel8.setText("jLabel8");

        jLabel15.setText("Access Forms:");

        buttonFamilyHisForm.setText("Family History Form");
        buttonFamilyHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFamilyHisFormActionPerformed(evt);
            }
        });

        jLabel28.setText("Tobacco::");

        jLabel29.setText("Alcohol:");

        jLabel5.setText("Tobacco Quanity:");

        jLabel6.setText("Tobacco Duration:");

        buttonCloseGenMedHisForm.setText("Close");
        buttonCloseGenMedHisForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseGenMedHisFormActionPerformed(evt);
            }
        });

        jLabel7.setText("Blood Type:");

        jLabel9.setText("rH Factor:");

        Rh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RhActionPerformed(evt);
            }
        });

        jLabel10.setText("Alcohol Quanity:");

        jLabel11.setText("Alcohol Duration:");

        jLabel12.setText("Drug:");

        jLabel13.setText("Drug Type:");

        jLabel14.setText("Drug Duration:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "General Medical History ID", "Blood Type"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout GeneralMedicalHistoryLayout = new javax.swing.GroupLayout(GeneralMedicalHistory);
        GeneralMedicalHistory.setLayout(GeneralMedicalHistoryLayout);
        GeneralMedicalHistoryLayout.setHorizontalGroup(
            GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(726, 726, 726))
            .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                            .addComponent(buttonAddGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonEditGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonDeleteGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonSaveGenMedHis)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(buttonCloseGenMedHisForm))
                        .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                    .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(GeneralMedicalHistoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(BloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(Rh, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(86, 86, 86))
                                        .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(58, 58, 58)))
                                    .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                                            .addGap(107, 107, 107)
                                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel15)
                                                .addComponent(buttonAllergyHisForm)
                                                .addComponent(buttonFamilyHisForm)))
                                        .addComponent(buttonImmunizationHisForm, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(buttonMedicationHisForm, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addComponent(buttonGenHisAutoInterview, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, GeneralMedicalHistoryLayout.createSequentialGroup()
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel29)
                                .addComponent(jLabel12)
                                .addComponent(jLabel5)
                                .addComponent(jLabel28))
                            .addGap(18, 18, 18)
                            .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Tobacco)
                                .addComponent(Drugduration)
                                .addComponent(TobaccoQuanity)
                                .addComponent(TobaccoDuration)
                                .addComponent(AlcoholQuanity)
                                .addComponent(Alcoholduration)
                                .addComponent(Drug)
                                .addComponent(DrugType)
                                .addComponent(Alcohol))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        GeneralMedicalHistoryLayout.setVerticalGroup(
            GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel15)
                        .addGap(8, 8, 8)
                        .addComponent(buttonAllergyHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonFamilyHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonImmunizationHisForm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMedicationHisForm))
                    .addGroup(GeneralMedicalHistoryLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddGenMedHis)
                    .addComponent(buttonEditGenMedHis)
                    .addComponent(buttonDeleteGenMedHis)
                    .addComponent(buttonSaveGenMedHis)
                    .addComponent(buttonCloseGenMedHisForm))
                .addGap(18, 18, 18)
                .addComponent(buttonGenHisAutoInterview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GeneralMedicalHistoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Rh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(BloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Tobacco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TobaccoQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TobaccoDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(Alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(AlcoholQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Alcoholduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Drug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DrugType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GeneralMedicalHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(Drugduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralMedicalHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GeneralMedicalHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMedicationHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMedicationHisFormActionPerformed
        // TODO add your handling code here:
         //calls Medication History Form
        MedicationHistory form = new MedicationHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonMedicationHisFormActionPerformed

    private void buttonSaveGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveGenMedHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSaveGenMedHisActionPerformed

    private void RhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RhActionPerformed

    private void buttonEditGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditGenMedHisActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonEditGenMedHisActionPerformed

    private void buttonAllergyHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAllergyHisFormActionPerformed
        // TODO add your handling code here:
        // calls Allergy Form
        AllergyHistory form = new AllergyHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonAllergyHisFormActionPerformed

    private void buttonFamilyHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFamilyHisFormActionPerformed
        // TODO add your handling code here:
        //calls Familiy History Form
        FamilyHistory form = new FamilyHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonFamilyHisFormActionPerformed

    private void buttonImmunizationHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonImmunizationHisFormActionPerformed
        // TODO add your handling code here:
        // calls Immunization Form
        ImmunizationHistory form = new ImmunizationHistory();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonImmunizationHisFormActionPerformed

    private void buttonAddGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddGenMedHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAddGenMedHisActionPerformed

    private void buttonDeleteGenMedHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteGenMedHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDeleteGenMedHisActionPerformed

    private void buttonCloseGenMedHisFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseGenMedHisFormActionPerformed
        // TODO add your handling code here:
        //goes back to Patient Demographic Form
        //calls Medication History Form
        PatientDemographics form = new PatientDemographics ();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonCloseGenMedHisFormActionPerformed

    private void buttonGenHisAutoInterviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenHisAutoInterviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGenHisAutoInterviewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneralMedicalHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneralMedicalHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alcohol;
    private javax.swing.JTextField AlcoholQuanity;
    private javax.swing.JTextField Alcoholduration;
    private javax.swing.JTextField BloodType;
    private javax.swing.JTextField Drug;
    private javax.swing.JTextField DrugType;
    private javax.swing.JTextField Drugduration;
    private javax.swing.JPanel GeneralMedicalHistory;
    private javax.swing.JTextField GeneralMedicalHistoryID;
    private javax.swing.JTextField Rh;
    private javax.swing.JTextField Tobacco;
    private javax.swing.JTextField TobaccoDuration;
    private javax.swing.JTextField TobaccoQuanity;
    private javax.swing.JButton buttonAddGenMedHis;
    private javax.swing.JButton buttonAllergyHisForm;
    private javax.swing.JButton buttonCloseGenMedHisForm;
    private javax.swing.JButton buttonDeleteGenMedHis;
    private javax.swing.JButton buttonEditGenMedHis;
    private javax.swing.JButton buttonFamilyHisForm;
    private javax.swing.JButton buttonGenHisAutoInterview;
    private javax.swing.JButton buttonImmunizationHisForm;
    private javax.swing.JButton buttonMedicationHisForm;
    private javax.swing.JButton buttonSaveGenMedHis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
